#!/bin/bash

# Content type header
echo "Content-type: application/json"
echo ""

# This script fetches the watchCat parameters from the /tmp/watchcat.json and returns it as JSON
# Example content of /tmp/watchcat.json:
# {"enabled": true, "track_ip": "1.1.1.1", "ping_timeout": 30, "ping_failure_count": 10}

# Check if the file exists
JSON_FILE="/tmp/watchcat.json"
if [ -f "$JSON_FILE" ]; then
    cat "$JSON_FILE"
else
    # return an empty JSON object
    echo "{}"
fi
